---
# Defines tasks to install and configure Postfix

- name: Include the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - common
    - postfix

- name: Install packages for RedHat derivatives
  yum: pkg={{ item }} state=present 
  with_items: postfix_packages
  when: ansible_os_family == 'RedHat'
  tags:
    - common
    - postfix

# - name: Write SMTP authentication template
  # template: >
    # src=sasl_passwd.j2
    # dest={{ postfix_config_dir }}/sasl_passwd
    # mode=0600 owner=root group=root
  # notify:
    # - postmap sasl
  # when: postfix_use_smtp and postfix_relayhost_user and postfix_relayhost_pass
  # tags:
    # - common
    # - postfix

- name: Write Postfix configuration template
  template: >
    src=main.cf.j2
    dest={{ postfix_config_dir }}/main.cf
    mode=0644 owner=root group=root
    backup=yes
  notify:
    - restart postfix
    - send test email
  tags:
    - common
    - postfix

- file: path={{ item }} state=directory mode=660 recurse=yes
  with_items:
    - ~/Maildir/new
    - ~/Maildir/cur
    - ~/Maildir/tmp

- name: Start Postfix on server boot
  service: >
    name={{ postfix_service }}
    state=started
    enabled=yes
  tags:
    - common
    - postfix
